[package]
name = "day01"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
rayon = "1.10.0"

[dev-dependencies]
divan = "0.1.16"

[[bench]]
name = "part1"
harness = false

[[bench]]
name = "part2"
harness = false
